version: '3.8'
services:
  client-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVER_PORT=8181
      - DB_HOST=postgres
      - DB_NAME=bookstore
    restart: on-failure

  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_DB: bookstore
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 5
