spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:bookstore}?reWriteBatchedInserts=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:310892}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          use_get_generated_keys: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: ${JWT_AUDIENCES:https://dev-kugzqddea6xf2itb.us.auth0.com/api/v2/}
          issuer-uri: ${JWT_ISSUER_URI:https://dev-kugzqddea6xf2itb.us.auth0.com/}
server:
  servlet:
    contextPath: /api
  error:
    include-message: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html

auth0:
  token:
    url: ${AUTH0_TOKEN_URL:https://dev-kugzqddea6xf2itb.us.auth0.com/oauth/token}
  client:
    id: ${AUTH0_CLIENT_ID:BQbD6HsCyR7rLxGACqTAELsOeI012dvj}
    secret: ${AUTH0_SECRET:FQxTzNVd_oPFdQ8vaBPotl7p-l2KDkWYiUvWToVroRM0kudQvANMpvJKyIturYyP}