spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:bookstore}?reWriteBatchedInserts=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:310892}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          use_get_generated_keys: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    contextPath: /api
